// Generated by CoffeeScript 2.1.0
(function() {
  'use strict';
  var acl;

  acl = {};

  //#####################################################################
  // middleware
  //#####################################################################
  acl.allowManager = function(req, res, next) {
    switch (req.token.uclass) {
      case UCLASS.ADMIN:
        return next();
      case UCLASS.USER:
        return res.status(400).json({
          data: RCODE.INVALID_PERMISSION
        });
      default:
        return res.status(400).json({
          data: RCODE.INVALID_PERMISSION
        });
    }
  };

  module.exports = acl;

}).call(this);

//# sourceMappingURL=acl.js.map
